export const Countries = [
	{
		code: "AF",
		name: "Afghanistan",
		currencyCode: "AFN",
		phoneCode: 93,
		provinces: []
	},
	{
		code: "AX",
		name: "Aland Islands",
		currencyCode: "EUR",
		phoneCode: 35818,
		provinces: []
	},
	{
		code: "AL",
		name: "Albania",
		currencyCode: "ALL",
		phoneCode: 355,
		provinces: []
	},
	{
		code: "DZ",
		name: "Algeria",
		currencyCode: "DZD",
		phoneCode: 213,
		provinces: []
	},
	{
		code: "AD",
		name: "Andorra",
		currencyCode: "EUR",
		phoneCode: 376,
		provinces: []
	},
	{
		code: "AO",
		name: "Angola",
		currencyCode: "AOA",
		phoneCode: 244,
		provinces: []
	},
	{
		code: "AI",
		name: "Anguilla",
		currencyCode: "XCD",
		phoneCode: 1264,
		provinces: []
	},
	{
		code: "AG",
		name: "Antigua And Barbuda",
		currencyCode: "XCD",
		phoneCode: 1268,
		provinces: []
	},
	{
		code: "AR",
		name: "Argentina",
		currencyCode: "ARS",
		phoneCode: 54,
		provinces: [
			{ code: "B", name: "Buenos Aires" },
			{ code: "K", name: "Catamarca" },
			{ code: "H", name: "Chaco" },
			{ code: "U", name: "Chubut" },
			{ code: "C", name: "Ciudad Autónoma de Buenos Aires" },
			{ code: "X", name: "Córdoba" },
			{ code: "W", name: "Corrientes" },
			{ code: "E", name: "Entre Ríos" },
			{ code: "P", name: "Formosa" },
			{ code: "Y", name: "Jujuy" },
			{ code: "L", name: "La Pampa" },
			{ code: "F", name: "La Rioja" },
			{ code: "M", name: "Mendoza" },
			{ code: "N", name: "Misiones" },
			{ code: "Q", name: "Neuquén" },
			{ code: "R", name: "Río Negro" },
			{ code: "A", name: "Salta" },
			{ code: "J", name: "San Juan" },
			{ code: "D", name: "San Luis" },
			{ code: "Z", name: "Santa Cruz" },
			{ code: "S", name: "Santa Fe" },
			{ code: "G", name: "Santiago Del Estero" },
			{ code: "V", name: "Tierra Del Fuego" },
			{ code: "T", name: "Tucumán" }
		]
	},
	{
		code: "AM",
		name: "Armenia",
		currencyCode: "AMD",
		phoneCode: 374,
		provinces: []
	},
	{
		code: "AW",
		name: "Aruba",
		currencyCode: "AWG",
		phoneCode: 297,
		provinces: []
	},
	{
		code: "AC",
		name: "Ascension Island",
		currencyCode: "SHP",
		phoneCode: 247,
		provinces: []
	},
	{
		code: "AU",
		name: "Australia",
		currencyCode: "AUD",
		phoneCode: 61,
		provinces: [
			{ code: "ACT", name: "Australian Capital Territory" },
			{ code: "NSW", name: "New South Wales" },
			{ code: "NT", name: "Northern Territory" },
			{ code: "QLD", name: "Queensland" },
			{ code: "SA", name: "South Australia" },
			{ code: "TAS", name: "Tasmania" },
			{ code: "VIC", name: "Victoria" },
			{ code: "WA", name: "Western Australia" }
		]
	},
	{
		code: "AT",
		name: "Austria",
		currencyCode: "EUR",
		phoneCode: 43,
		provinces: []
	},
	{
		code: "AZ",
		name: "Azerbaijan",
		currencyCode: "AZN",
		phoneCode: 994,
		provinces: []
	},
	{
		code: "BS",
		name: "Bahamas",
		currencyCode: "BSD",
		phoneCode: 1242,
		provinces: []
	},
	{
		code: "BH",
		name: "Bahrain",
		currencyCode: "",
		phoneCode: 973,
		provinces: []
	},
	{
		code: "BD",
		name: "Bangladesh",
		currencyCode: "BDT",
		phoneCode: 880,
		provinces: []
	},
	{
		code: "BB",
		name: "Barbados",
		currencyCode: "BBD",
		phoneCode: 1246,
		provinces: []
	},
	{
		code: "BY",
		name: "Belarus",
		currencyCode: "",
		phoneCode: 375,
		provinces: []
	},
	{
		code: "BE",
		name: "Belgium",
		currencyCode: "EUR",
		phoneCode: 32,
		provinces: []
	},
	{
		code: "BZ",
		name: "Belize",
		currencyCode: "BZD",
		phoneCode: 501,
		provinces: []
	},
	{
		code: "BJ",
		name: "Benin",
		currencyCode: "XOF",
		phoneCode: 229,
		provinces: []
	},
	{
		code: "BM",
		name: "Bermuda",
		currencyCode: "USD",
		phoneCode: 1441,
		provinces: []
	},
	{
		code: "BT",
		name: "Bhutan",
		currencyCode: "INR",
		phoneCode: 975,
		provinces: []
	},
	{
		code: "BO",
		name: "Bolivia",
		currencyCode: "BOB",
		phoneCode: 591,
		provinces: []
	},
	{
		code: "BA",
		name: "Bosnia And Herzegovina",
		currencyCode: "BAM",
		phoneCode: 387,
		provinces: []
	},
	{
		code: "BW",
		name: "Botswana",
		currencyCode: "BWP",
		phoneCode: 267,
		provinces: []
	},
	{
		code: "BR",
		name: "Brazil",
		currencyCode: "BRL",
		phoneCode: 55,
		provinces: [
			{ code: "AC", name: "Acre" },
			{ code: "AL", name: "Alagoas" },
			{ code: "AP", name: "Amapá" },
			{ code: "AM", name: "Amazonas" },
			{ code: "BA", name: "Bahia" },
			{ code: "CE", name: "Ceará" },
			{ code: "DF", name: "Distrito Federal" },
			{ code: "ES", name: "Espírito Santo" },
			{ code: "GO", name: "Goiás" },
			{ code: "MA", name: "Maranhão" },
			{ code: "MT", name: "Mato Grosso" },
			{ code: "MS", name: "Mato Grosso do Sul" },
			{ code: "MG", name: "Minas Gerais" },
			{ code: "PA", name: "Pará" },
			{ code: "PB", name: "Paraíba" },
			{ code: "PR", name: "Paraná" },
			{ code: "PE", name: "Pernambuco" },
			{ code: "PI", name: "Piauí" },
			{ code: "RJ", name: "Rio de Janeiro" },
			{ code: "RN", name: "Rio Grande do Norte" },
			{ code: "RS", name: "Rio Grande do Sul" },
			{ code: "RO", name: "Rondônia" },
			{ code: "RR", name: "Roraima" },
			{ code: "SC", name: "Santa Catarina" },
			{ code: "SP", name: "São Paulo" },
			{ code: "SE", name: "Sergipe" },
			{ code: "TO", name: "Tocantins" }
		]
	},
	{
		code: "IO",
		name: "British Indian Ocean Territory",
		currencyCode: "USD",
		phoneCode: 246,
		provinces: []
	},
	{
		code: "BN",
		name: "Brunei",
		currencyCode: "BND",
		phoneCode: 673,
		provinces: []
	},
	{
		code: "BG",
		name: "Bulgaria",
		currencyCode: "BGN",
		phoneCode: 359,
		provinces: []
	},
	{
		code: "BF",
		name: "Burkina Faso",
		currencyCode: "XOF",
		phoneCode: 226,
		provinces: []
	},
	{
		code: "BI",
		name: "Burundi",
		currencyCode: "BIF",
		phoneCode: 257,
		provinces: []
	},
	{
		code: "KH",
		name: "Cambodia",
		currencyCode: "KHR",
		phoneCode: 855,
		provinces: []
	},
	{
		code: "CA",
		name: "Canada",
		currencyCode: "CAD",
		phoneCode: 1,
		provinces: [
			{ code: "AB", name: "Alberta" },
			{ code: "BC", name: "British Columbia" },
			{ code: "MB", name: "Manitoba" },
			{ code: "NB", name: "New Brunswick" },
			{ code: "NL", name: "Newfoundland and Labrador" },
			{ code: "NT", name: "Northwest Territories" },
			{ code: "NS", name: "Nova Scotia" },
			{ code: "NU", name: "Nunavut" },
			{ code: "ON", name: "Ontario" },
			{ code: "PE", name: "Prince Edward Island" },
			{ code: "QC", name: "Quebec" },
			{ code: "SK", name: "Saskatchewan" },
			{ code: "YT", name: "Yukon" }
		]
	},
	{
		code: "CV",
		name: "Cape Verde",
		currencyCode: "CVE",
		phoneCode: 238,
		provinces: []
	},
	{
		code: "BQ",
		name: "Caribbean Netherlands",
		currencyCode: "USD",
		phoneCode: 599,
		provinces: []
	},
	{
		code: "KY",
		name: "Cayman Islands",
		currencyCode: "KYD",
		phoneCode: 1345,
		provinces: []
	},
	{
		code: "CF",
		name: "Central African Republic",
		currencyCode: "XAF",
		phoneCode: 236,
		provinces: []
	},
	{
		code: "TD",
		name: "Chad",
		currencyCode: "XAF",
		phoneCode: 235,
		provinces: []
	},
	{
		code: "CL",
		name: "Chile",
		currencyCode: "CLP",
		phoneCode: 56,
		provinces: [
			{ code: "AN", name: "Antofagasta" },
			{ code: "AR", name: "Araucanía" },
			{ code: "AP", name: "Arica and Parinacota" },
			{ code: "AT", name: "Atacama" },
			{ code: "AI", name: "Aysén" },
			{ code: "BI", name: "Biobío" },
			{ code: "CO", name: "Coquimbo" },
			{ code: "LL", name: "Los Lagos" },
			{ code: "LR", name: "Los Ríos" },
			{ code: "MA", name: "Magallanes" },
			{ code: "ML", name: "Maule" },
			{ code: "NB", name: "Ñuble" },
			{ code: "LI", name: "O'Higgins" },
			{ code: "RM", name: "Santiago" },
			{ code: "TA", name: "Tarapacá" },
			{ code: "VS", name: "Valparaíso" }
		]
	},
	{
		code: "CN",
		name: "China",
		currencyCode: "CNY",
		phoneCode: 86,
		provinces: [
			{ code: "AH", name: "Anhui" },
			{ code: "BJ", name: "Beijing" },
			{ code: "CQ", name: "Chongqing" },
			{ code: "FJ", name: "Fujian" },
			{ code: "GS", name: "Gansu" },
			{ code: "GD", name: "Guangdong" },
			{ code: "GX", name: "Guangxi" },
			{ code: "GZ", name: "Guizhou" },
			{ code: "HI", name: "Hainan" },
			{ code: "HE", name: "Hebei" },
			{ code: "HL", name: "Heilongjiang" },
			{ code: "HA", name: "Henan" },
			{ code: "HB", name: "Hubei" },
			{ code: "HN", name: "Hunan" },
			{ code: "NM", name: "Inner Mongolia" },
			{ code: "JS", name: "Jiangsu" },
			{ code: "JX", name: "Jiangxi" },
			{ code: "JL", name: "Jilin" },
			{ code: "LN", name: "Liaoning" },
			{ code: "NX", name: "Ningxia" },
			{ code: "QH", name: "Qinghai" },
			{ code: "SN", name: "Shaanxi" },
			{ code: "SD", name: "Shandong" },
			{ code: "SH", name: "Shanghai" },
			{ code: "SX", name: "Shanxi" },
			{ code: "SC", name: "Sichuan" },
			{ code: "TJ", name: "Tianjin" },
			{ code: "XJ", name: "Xinjiang" },
			{ code: "YZ", name: "Xizang" },
			{ code: "YN", name: "Yunnan" },
			{ code: "ZJ", name: "Zhejiang" }
		]
	},
	{
		code: "CX",
		name: "Christmas Island",
		currencyCode: "AUD",
		phoneCode: 61,
		provinces: []
	},
	{
		code: "CC",
		name: "Cocos (Keeling) Islands",
		currencyCode: "AUD",
		phoneCode: 61,
		provinces: []
	},
	{
		code: "CO",
		name: "Colombia",
		currencyCode: "COP",
		phoneCode: 57,
		provinces: [
			{ code: "AMA", name: "Amazonas" },
			{ code: "ANT", name: "Antioquia" },
			{ code: "ARA", name: "Arauca" },
			{ code: "ATL", name: "Atlántico" },
			{ code: "DC", name: "Bogotá, D.C." },
			{ code: "BOL", name: "Bolívar" },
			{ code: "BOY", name: "Boyacá" },
			{ code: "CAL", name: "Caldas" },
			{ code: "CAQ", name: "Caquetá" },
			{ code: "CAS", name: "Casanare" },
			{ code: "CAU", name: "Cauca" },
			{ code: "CES", name: "Cesar" },
			{ code: "CHO", name: "Chocó" },
			{ code: "COR", name: "Córdoba" },
			{ code: "CUN", name: "Cundinamarca" },
			{ code: "GUA", name: "Guainía" },
			{ code: "GUV", name: "Guaviare" },
			{ code: "HUI", name: "Huila" },
			{ code: "LAG", name: "La Guajira" },
			{ code: "MAG", name: "Magdalena" },
			{ code: "MET", name: "Meta" },
			{ code: "NAR", name: "Nariño" },
			{ code: "NSA", name: "Norte de Santander" },
			{ code: "PUT", name: "Putumayo" },
			{ code: "QUI", name: "Quindío" },
			{ code: "RIS", name: "Risaralda" },
			{ code: "SAP", name: "San Andrés, Providencia y Santa Catalina" },
			{ code: "SAN", name: "Santander" },
			{ code: "SUC", name: "Sucre" },
			{ code: "TOL", name: "Tolima" },
			{ code: "VAC", name: "Valle del Cauca" },
			{ code: "VAU", name: "Vaupés" },
			{ code: "VID", name: "Vichada" }
		]
	},
	{
		code: "KM",
		name: "Comoros",
		currencyCode: "KMF",
		phoneCode: 269,
		provinces: []
	},
	{
		code: "CG",
		name: "Congo",
		currencyCode: "XAF",
		phoneCode: 242,
		provinces: []
	},
	{
		code: "CD",
		name: "Congo, The Democratic Republic Of The",
		currencyCode: "CDF",
		phoneCode: 243,
		provinces: []
	},
	{
		code: "CK",
		name: "Cook Islands",
		currencyCode: "NZD",
		phoneCode: 682,
		provinces: []
	},
	{
		code: "CR",
		name: "Costa Rica",
		currencyCode: "CRC",
		phoneCode: 506,
		provinces: [
			{ code: "CR-A", name: "Alajuela" },
			{ code: "CR-C", name: "Cartago" },
			{ code: "CR-G", name: "Guanacaste" },
			{ code: "CR-H", name: "Heredia" },
			{ code: "CR-L", name: "Limón" },
			{ code: "CR-P", name: "Puntarenas" },
			{ code: "CR-SJ", name: "San José" }
		]
	},
	{
		code: "HR",
		name: "Croatia",
		currencyCode: "EUR",
		phoneCode: 385,
		provinces: []
	},
	{
		code: "CW",
		name: "Curaçao",
		currencyCode: "ANG",
		phoneCode: 599,
		provinces: []
	},
	{
		code: "CY",
		name: "Cyprus",
		currencyCode: "EUR",
		phoneCode: 357,
		provinces: []
	},
	{
		code: "CZ",
		name: "Czech Republic",
		currencyCode: "CZK",
		phoneCode: 420,
		provinces: []
	},
	{
		code: "CI",
		name: "Côte d'Ivoire",
		currencyCode: "XOF",
		phoneCode: 225,
		provinces: []
	},
	{
		code: "DK",
		name: "Denmark",
		currencyCode: "DKK",
		phoneCode: 45,
		provinces: []
	},
	{
		code: "DJ",
		name: "Djibouti",
		currencyCode: "DJF",
		phoneCode: 253,
		provinces: []
	},
	{
		code: "DM",
		name: "Dominica",
		currencyCode: "XCD",
		phoneCode: 1767,
		provinces: []
	},
	{
		code: "DO",
		name: "Dominican Republic",
		currencyCode: "DOP",
		phoneCode: 1,
		provinces: []
	},
	{
		code: "EC",
		name: "Ecuador",
		currencyCode: "USD",
		phoneCode: 593,
		provinces: []
	},
	{
		code: "EG",
		name: "Egypt",
		currencyCode: "EGP",
		phoneCode: 20,
		provinces: [
			{ code: "SU", name: "6th of October" },
			{ code: "SHR", name: "Al Sharqia" },
			{ code: "ALX", name: "Alexandria" },
			{ code: "ASN", name: "Aswan" },
			{ code: "AST", name: "Asyut" },
			{ code: "BH", name: "Beheira" },
			{ code: "BNS", name: "Beni Suef" },
			{ code: "C", name: "Cairo" },
			{ code: "DK", name: "Dakahlia" },
			{ code: "DT", name: "Damietta" },
			{ code: "FYM", name: "Faiyum" },
			{ code: "GH", name: "Gharbia" },
			{ code: "GZ", name: "Giza" },
			{ code: "HU", name: "Helwan" },
			{ code: "IS", name: "Ismailia" },
			{ code: "KFS", name: "Kafr el-Sheikh" },
			{ code: "LX", name: "Luxor" },
			{ code: "MT", name: "Matrouh" },
			{ code: "MN", name: "Minya" },
			{ code: "MNF", name: "Monufia" },
			{ code: "WAD", name: "New Valley" },
			{ code: "SIN", name: "North Sinai" },
			{ code: "PTS", name: "Port Said" },
			{ code: "KB", name: "Qalyubia" },
			{ code: "KN", name: "Qena" },
			{ code: "BA", name: "Red Sea" },
			{ code: "SHG", name: "Sohag" },
			{ code: "JS", name: "South Sinai" },
			{ code: "SUZ", name: "Suez" }
		]
	},
	{
		code: "SV",
		name: "El Salvador",
		currencyCode: "USD",
		phoneCode: 503,
		provinces: [
			{ code: "SV-AH", name: "Ahuachapán" },
			{ code: "SV-CA", name: "Cabañas" },
			{ code: "SV-CH", name: "Chalatenango" },
			{ code: "SV-CU", name: "Cuscatlán" },
			{ code: "SV-LI", name: "La Libertad" },
			{ code: "SV-PA", name: "La Paz" },
			{ code: "SV-UN", name: "La Unión" },
			{ code: "SV-MO", name: "Morazán" },
			{ code: "SV-SM", name: "San Miguel" },
			{ code: "SV-SS", name: "San Salvador" },
			{ code: "SV-SV", name: "San Vicente" },
			{ code: "SV-SA", name: "Santa Ana" },
			{ code: "SV-SO", name: "Sonsonate" },
			{ code: "SV-US", name: "Usulután" }
		]
	},
	{
		code: "GQ",
		name: "Equatorial Guinea",
		currencyCode: "XAF",
		phoneCode: 240,
		provinces: []
	},
	{
		code: "ER",
		name: "Eritrea",
		currencyCode: "",
		phoneCode: 291,
		provinces: []
	},
	{
		code: "EE",
		name: "Estonia",
		currencyCode: "EUR",
		phoneCode: 372,
		provinces: []
	},
	{
		code: "SZ",
		name: "Eswatini",
		currencyCode: "SZL",
		phoneCode: 268,
		provinces: []
	},
	{
		code: "ET",
		name: "Ethiopia",
		currencyCode: "ETB",
		phoneCode: 251,
		provinces: []
	},
	{
		code: "FK",
		name: "Falkland Islands (Malvinas)",
		currencyCode: "FKP",
		phoneCode: 500,
		provinces: []
	},
	{
		code: "FO",
		name: "Faroe Islands",
		currencyCode: "DKK",
		phoneCode: 298,
		provinces: []
	},
	{
		code: "FJ",
		name: "Fiji",
		currencyCode: "FJD",
		phoneCode: 679,
		provinces: []
	},
	{
		code: "FI",
		name: "Finland",
		currencyCode: "EUR",
		phoneCode: 358,
		provinces: []
	},
	{
		code: "FR",
		name: "France",
		currencyCode: "EUR",
		phoneCode: 33,
		provinces: []
	},
	{
		code: "GF",
		name: "French Guiana",
		currencyCode: "EUR",
		phoneCode: 594,
		provinces: []
	},
	{
		code: "PF",
		name: "French Polynesia",
		currencyCode: "XPF",
		phoneCode: 689,
		provinces: []
	},
	{
		code: "TF",
		name: "French Southern Territories",
		currencyCode: "EUR",
		phoneCode: 262,
		provinces: []
	},
	{
		code: "GA",
		name: "Gabon",
		currencyCode: "XOF",
		phoneCode: 241,
		provinces: []
	},
	{
		code: "GM",
		name: "Gambia",
		currencyCode: "GMD",
		phoneCode: 220,
		provinces: []
	},
	{
		code: "GE",
		name: "Georgia",
		currencyCode: "",
		phoneCode: 995,
		provinces: []
	},
	{
		code: "DE",
		name: "Germany",
		currencyCode: "EUR",
		phoneCode: 49,
		provinces: []
	},
	{
		code: "GH",
		name: "Ghana",
		currencyCode: "",
		phoneCode: 233,
		provinces: []
	},
	{
		code: "GI",
		name: "Gibraltar",
		currencyCode: "GBP",
		phoneCode: 350,
		provinces: []
	},
	{
		code: "GR",
		name: "Greece",
		currencyCode: "EUR",
		phoneCode: 30,
		provinces: []
	},
	{
		code: "GL",
		name: "Greenland",
		currencyCode: "DKK",
		phoneCode: 299,
		provinces: []
	},
	{
		code: "GD",
		name: "Grenada",
		currencyCode: "XCD",
		phoneCode: 1473,
		provinces: []
	},
	{
		code: "GP",
		name: "Guadeloupe",
		currencyCode: "EUR",
		phoneCode: 590,
		provinces: []
	},
	{
		code: "GT",
		name: "Guatemala",
		currencyCode: "GTQ",
		phoneCode: 502,
		provinces: [
			{ code: "AVE", name: "Alta Verapaz" },
			{ code: "BVE", name: "Baja Verapaz" },
			{ code: "CMT", name: "Chimaltenango" },
			{ code: "CQM", name: "Chiquimula" },
			{ code: "EPR", name: "El Progreso" },
			{ code: "ESC", name: "Escuintla" },
			{ code: "GUA", name: "Guatemala" },
			{ code: "HUE", name: "Huehuetenango" },
			{ code: "IZA", name: "Izabal" },
			{ code: "JAL", name: "Jalapa" },
			{ code: "JUT", name: "Jutiapa" },
			{ code: "PET", name: "Petén" },
			{ code: "QUE", name: "Quetzaltenango" },
			{ code: "QUI", name: "Quiché" },
			{ code: "RET", name: "Retalhuleu" },
			{ code: "SAC", name: "Sacatepéquez" },
			{ code: "SMA", name: "San Marcos" },
			{ code: "SRO", name: "Santa Rosa" },
			{ code: "SOL", name: "Sololá" },
			{ code: "SUC", name: "Suchitepéquez" },
			{ code: "TOT", name: "Totonicapán" },
			{ code: "ZAC", name: "Zacapa" }
		]
	},
	{
		code: "GG",
		name: "Guernsey",
		currencyCode: "GBP",
		phoneCode: 44,
		provinces: []
	},
	{
		code: "GN",
		name: "Guinea",
		currencyCode: "GNF",
		phoneCode: 224,
		provinces: []
	},
	{
		code: "GW",
		name: "Guinea Bissau",
		currencyCode: "XOF",
		phoneCode: 245,
		provinces: []
	},
	{
		code: "GY",
		name: "Guyana",
		currencyCode: "GYD",
		phoneCode: 592,
		provinces: []
	},
	{
		code: "HT",
		name: "Haiti",
		currencyCode: "HTG",
		phoneCode: 509,
		provinces: []
	},
	{
		code: "VA",
		name: "Holy See (Vatican City State)",
		currencyCode: "EUR",
		phoneCode: 3,
		provinces: []
	},
	{
		code: "HN",
		name: "Honduras",
		currencyCode: "HNL",
		phoneCode: 504,
		provinces: []
	},
	{
		code: "HK",
		name: "Hong Kong",
		currencyCode: "HKD",
		phoneCode: 852,
		provinces: [
			{ code: "HK", name: "Hong Kong Island" },
			{ code: "KL", name: "Kowloon" },
			{ code: "NT", name: "New Territories" }
		]
	},
	{
		code: "HU",
		name: "Hungary",
		currencyCode: "HUF",
		phoneCode: 36,
		provinces: []
	},
	{
		code: "IS",
		name: "Iceland",
		currencyCode: "ISK",
		phoneCode: 354,
		provinces: []
	},
	{
		code: "IN",
		name: "India",
		currencyCode: "INR",
		phoneCode: 91,
		provinces: [
			{ code: "AN", name: "Andaman and Nicobar Islands" },
			{ code: "AP", name: "Andhra Pradesh" },
			{ code: "AR", name: "Arunachal Pradesh" },
			{ code: "AS", name: "Assam" },
			{ code: "BR", name: "Bihar" },
			{ code: "CH", name: "Chandigarh" },
			{ code: "CG", name: "Chhattisgarh" },
			{ code: "DN", name: "Dadra and Nagar Haveli" },
			{ code: "DD", name: "Daman and Diu" },
			{ code: "DL", name: "Delhi" },
			{ code: "GA", name: "Goa" },
			{ code: "GJ", name: "Gujarat" },
			{ code: "HR", name: "Haryana" },
			{ code: "HP", name: "Himachal Pradesh" },
			{ code: "JK", name: "Jammu and Kashmir" },
			{ code: "JH", name: "Jharkhand" },
			{ code: "KA", name: "Karnataka" },
			{ code: "KL", name: "Kerala" },
			{ code: "LA", name: "Ladakh" },
			{ code: "LD", name: "Lakshadweep" },
			{ code: "MP", name: "Madhya Pradesh" },
			{ code: "MH", name: "Maharashtra" },
			{ code: "MN", name: "Manipur" },
			{ code: "ML", name: "Meghalaya" },
			{ code: "MZ", name: "Mizoram" },
			{ code: "NL", name: "Nagaland" },
			{ code: "OR", name: "Odisha" },
			{ code: "PY", name: "Puducherry" },
			{ code: "PB", name: "Punjab" },
			{ code: "RJ", name: "Rajasthan" },
			{ code: "SK", name: "Sikkim" },
			{ code: "TN", name: "Tamil Nadu" },
			{ code: "TS", name: "Telangana" },
			{ code: "TR", name: "Tripura" },
			{ code: "UP", name: "Uttar Pradesh" },
			{ code: "UK", name: "Uttarakhand" },
			{ code: "WB", name: "West Bengal" }
		]
	},
	{
		code: "ID",
		name: "Indonesia",
		currencyCode: "IDR",
		phoneCode: 62,
		provinces: [
			{ code: "AC", name: "Aceh" },
			{ code: "BA", name: "Bali" },
			{ code: "BB", name: "Bangka Belitung" },
			{ code: "BT", name: "Banten" },
			{ code: "BE", name: "Bengkulu" },
			{ code: "GO", name: "Gorontalo" },
			{ code: "JK", name: "Jakarta" },
			{ code: "JA", name: "Jambi" },
			{ code: "JB", name: "Jawa Barat" },
			{ code: "JT", name: "Jawa Tengah" },
			{ code: "JI", name: "Jawa Timur" },
			{ code: "KB", name: "Kalimantan Barat" },
			{ code: "KS", name: "Kalimantan Selatan" },
			{ code: "KT", name: "Kalimantan Tengah" },
			{ code: "KI", name: "Kalimantan Timur" },
			{ code: "KU", name: "Kalimantan Utara" },
			{ code: "KR", name: "Kepulauan Riau" },
			{ code: "LA", name: "Lampung" },
			{ code: "MA", name: "Maluku" },
			{ code: "MU", name: "Maluku Utara" },
			{ code: "SU", name: "North Sumatra" },
			{ code: "NB", name: "Nusa Tenggara Barat" },
			{ code: "NT", name: "Nusa Tenggara Timur" },
			{ code: "PA", name: "Papua" },
			{ code: "PB", name: "Papua Barat" },
			{ code: "RI", name: "Riau" },
			{ code: "SS", name: "South Sumatra" },
			{ code: "SR", name: "Sulawesi Barat" },
			{ code: "SN", name: "Sulawesi Selatan" },
			{ code: "ST", name: "Sulawesi Tengah" },
			{ code: "SG", name: "Sulawesi Tenggara" },
			{ code: "SA", name: "Sulawesi Utara" },
			{ code: "SB", name: "West Sumatra" },
			{ code: "YO", name: "Yogyakarta" }
		]
	},
	{
		code: "IQ",
		name: "Iraq",
		currencyCode: "",
		phoneCode: 964,
		provinces: []
	},
	{
		code: "IE",
		name: "Ireland",
		currencyCode: "EUR",
		phoneCode: 353,
		provinces: [
			{ code: "CW", name: "Carlow" },
			{ code: "CN", name: "Cavan" },
			{ code: "CE", name: "Clare" },
			{ code: "CO", name: "Cork" },
			{ code: "DL", name: "Donegal" },
			{ code: "D", name: "Dublin" },
			{ code: "G", name: "Galway" },
			{ code: "KY", name: "Kerry" },
			{ code: "KE", name: "Kildare" },
			{ code: "KK", name: "Kilkenny" },
			{ code: "LS", name: "Laois" },
			{ code: "LM", name: "Leitrim" },
			{ code: "LK", name: "Limerick" },
			{ code: "LD", name: "Longford" },
			{ code: "LH", name: "Louth" },
			{ code: "MO", name: "Mayo" },
			{ code: "MH", name: "Meath" },
			{ code: "MN", name: "Monaghan" },
			{ code: "OY", name: "Offaly" },
			{ code: "RN", name: "Roscommon" },
			{ code: "SO", name: "Sligo" },
			{ code: "TA", name: "Tipperary" },
			{ code: "WD", name: "Waterford" },
			{ code: "WH", name: "Westmeath" },
			{ code: "WX", name: "Wexford" },
			{ code: "WW", name: "Wicklow" }
		]
	},
	{
		code: "IM",
		name: "Isle Of Man",
		currencyCode: "GBP",
		phoneCode: 44,
		provinces: []
	},
	{
		code: "IL",
		name: "Israel",
		currencyCode: "ILS",
		phoneCode: 972,
		provinces: []
	},
	{
		code: "IT",
		name: "Italy",
		currencyCode: "EUR",
		phoneCode: 39,
		provinces: [
			{ code: "AG", name: "Agrigento" },
			{ code: "AL", name: "Alessandria" },
			{ code: "AN", name: "Ancona" },
			{ code: "AO", name: "Aosta" },
			{ code: "AR", name: "Arezzo" },
			{ code: "AP", name: "Ascoli Piceno" },
			{ code: "AT", name: "Asti" },
			{ code: "AV", name: "Avellino" },
			{ code: "BA", name: "Bari" },
			{ code: "BT", name: "Barletta-Andria-Trani" },
			{ code: "BL", name: "Belluno" },
			{ code: "BN", name: "Benevento" },
			{ code: "BG", name: "Bergamo" },
			{ code: "BI", name: "Biella" },
			{ code: "BO", name: "Bologna" },
			{ code: "BZ", name: "Bolzano" },
			{ code: "BS", name: "Brescia" },
			{ code: "BR", name: "Brindisi" },
			{ code: "CA", name: "Cagliari" },
			{ code: "CL", name: "Caltanissetta" },
			{ code: "CB", name: "Campobasso" },
			{ code: "CI", name: "Carbonia-Iglesias" },
			{ code: "CE", name: "Caserta" },
			{ code: "CT", name: "Catania" },
			{ code: "CZ", name: "Catanzaro" },
			{ code: "CH", name: "Chieti" },
			{ code: "CO", name: "Como" },
			{ code: "CS", name: "Cosenza" },
			{ code: "CR", name: "Cremona" },
			{ code: "KR", name: "Crotone" },
			{ code: "CN", name: "Cuneo" },
			{ code: "EN", name: "Enna" },
			{ code: "FM", name: "Fermo" },
			{ code: "FE", name: "Ferrara" },
			{ code: "FI", name: "Firenze" },
			{ code: "FG", name: "Foggia" },
			{ code: "FC", name: "Forlì-Cesena" },
			{ code: "FR", name: "Frosinone" },
			{ code: "GE", name: "Genova" },
			{ code: "GO", name: "Gorizia" },
			{ code: "GR", name: "Grosseto" },
			{ code: "IM", name: "Imperia" },
			{ code: "IS", name: "Isernia" },
			{ code: "AQ", name: "L'Aquila" },
			{ code: "SP", name: "La Spezia" },
			{ code: "LT", name: "Latina" },
			{ code: "LE", name: "Lecce" },
			{ code: "LC", name: "Lecco" },
			{ code: "LI", name: "Livorno" },
			{ code: "LO", name: "Lodi" },
			{ code: "LU", name: "Lucca" },
			{ code: "MC", name: "Macerata" },
			{ code: "MN", name: "Mantova" },
			{ code: "MS", name: "Massa-Carrara" },
			{ code: "MT", name: "Matera" },
			{ code: "VS", name: "Medio Campidano" },
			{ code: "ME", name: "Messina" },
			{ code: "MI", name: "Milano" },
			{ code: "MO", name: "Modena" },
			{ code: "MB", name: "Monza e Brianza" },
			{ code: "NA", name: "Napoli" },
			{ code: "NO", name: "Novara" },
			{ code: "NU", name: "Nuoro" },
			{ code: "OG", name: "Ogliastra" },
			{ code: "OT", name: "Olbia-Tempio" },
			{ code: "OR", name: "Oristano" },
			{ code: "PD", name: "Padova" },
			{ code: "PA", name: "Palermo" },
			{ code: "PR", name: "Parma" },
			{ code: "PV", name: "Pavia" },
			{ code: "PG", name: "Perugia" },
			{ code: "PU", name: "Pesaro e Urbino" },
			{ code: "PE", name: "Pescara" },
			{ code: "PC", name: "Piacenza" },
			{ code: "PI", name: "Pisa" },
			{ code: "PT", name: "Pistoia" },
			{ code: "PN", name: "Pordenone" },
			{ code: "PZ", name: "Potenza" },
			{ code: "PO", name: "Prato" },
			{ code: "RG", name: "Ragusa" },
			{ code: "RA", name: "Ravenna" },
			{ code: "RC", name: "Reggio Calabria" },
			{ code: "RE", name: "Reggio Emilia" },
			{ code: "RI", name: "Rieti" },
			{ code: "RN", name: "Rimini" },
			{ code: "RM", name: "Roma" },
			{ code: "RO", name: "Rovigo" },
			{ code: "SA", name: "Salerno" },
			{ code: "SS", name: "Sassari" },
			{ code: "SV", name: "Savona" },
			{ code: "SI", name: "Siena" },
			{ code: "SR", name: "Siracusa" },
			{ code: "SO", name: "Sondrio" },
			{ code: "TA", name: "Taranto" },
			{ code: "TE", name: "Teramo" },
			{ code: "TR", name: "Terni" },
			{ code: "TO", name: "Torino" },
			{ code: "TP", name: "Trapani" },
			{ code: "TN", name: "Trento" },
			{ code: "TV", name: "Treviso" },
			{ code: "TS", name: "Trieste" },
			{ code: "UD", name: "Udine" },
			{ code: "VA", name: "Varese" },
			{ code: "VE", name: "Venezia" },
			{ code: "VB", name: "Verbano-Cusio-Ossola" },
			{ code: "VC", name: "Vercelli" },
			{ code: "VR", name: "Verona" },
			{ code: "VV", name: "Vibo Valentia" },
			{ code: "VI", name: "Vicenza" },
			{ code: "VT", name: "Viterbo" }
		]
	},
	{
		code: "JM",
		name: "Jamaica",
		currencyCode: "JMD",
		phoneCode: 1,
		provinces: []
	},
	{
		code: "JP",
		name: "Japan",
		currencyCode: "JPY",
		phoneCode: 81,
		provinces: [
			{ code: "JP-23", name: "Aichi" },
			{ code: "JP-05", name: "Akita" },
			{ code: "JP-02", name: "Aomori" },
			{ code: "JP-12", name: "Chiba" },
			{ code: "JP-38", name: "Ehime" },
			{ code: "JP-18", name: "Fukui" },
			{ code: "JP-40", name: "Fukuoka" },
			{ code: "JP-07", name: "Fukushima" },
			{ code: "JP-21", name: "Gifu" },
			{ code: "JP-10", name: "Gunma" },
			{ code: "JP-34", name: "Hiroshima" },
			{ code: "JP-01", name: "Hokkaidō" },
			{ code: "JP-28", name: "Hyōgo" },
			{ code: "JP-08", name: "Ibaraki" },
			{ code: "JP-17", name: "Ishikawa" },
			{ code: "JP-03", name: "Iwate" },
			{ code: "JP-37", name: "Kagawa" },
			{ code: "JP-46", name: "Kagoshima" },
			{ code: "JP-14", name: "Kanagawa" },
			{ code: "JP-39", name: "Kōchi" },
			{ code: "JP-43", name: "Kumamoto" },
			{ code: "JP-26", name: "Kyōto" },
			{ code: "JP-24", name: "Mie" },
			{ code: "JP-04", name: "Miyagi" },
			{ code: "JP-45", name: "Miyazaki" },
			{ code: "JP-20", name: "Nagano" },
			{ code: "JP-42", name: "Nagasaki" },
			{ code: "JP-29", name: "Nara" },
			{ code: "JP-15", name: "Niigata" },
			{ code: "JP-44", name: "Ōita" },
			{ code: "JP-33", name: "Okayama" },
			{ code: "JP-47", name: "Okinawa" },
			{ code: "JP-27", name: "Ōsaka" },
			{ code: "JP-41", name: "Saga" },
			{ code: "JP-11", name: "Saitama" },
			{ code: "JP-25", name: "Shiga" },
			{ code: "JP-32", name: "Shimane" },
			{ code: "JP-22", name: "Shizuoka" },
			{ code: "JP-09", name: "Tochigi" },
			{ code: "JP-36", name: "Tokushima" },
			{ code: "JP-13", name: "Tōkyō" },
			{ code: "JP-31", name: "Tottori" },
			{ code: "JP-16", name: "Toyama" },
			{ code: "JP-30", name: "Wakayama" },
			{ code: "JP-06", name: "Yamagata" },
			{ code: "JP-35", name: "Yamaguchi" },
			{ code: "JP-19", name: "Yamanashi" }
		]
	},
	{
		code: "JE",
		name: "Jersey",
		currencyCode: "GBP",
		phoneCode: 44,
		provinces: []
	},
	{
		code: "JO",
		name: "Jordan",
		currencyCode: "",
		phoneCode: 962,
		provinces: []
	},
	{
		code: "KZ",
		name: "Kazakhstan",
		currencyCode: "KZT",
		phoneCode: 7,
		provinces: []
	},
	{
		code: "KE",
		name: "Kenya",
		currencyCode: "KES",
		phoneCode: 254,
		provinces: []
	},
	{
		code: "KI",
		name: "Kiribati",
		currencyCode: "AUD",
		phoneCode: 686,
		provinces: []
	},
	{
		code: "XK",
		name: "Kosovo",
		currencyCode: "EUR",
		phoneCode: 383,
		provinces: []
	},
	{
		code: "KW",
		name: "Kuwait",
		currencyCode: "",
		phoneCode: 965,
		provinces: [
			{ code: "KW-AH", name: "Al Ahmadi" },
			{ code: "KW-KU", name: "Al Asimah" },
			{ code: "KW-FA", name: "Al Farwaniyah" },
			{ code: "KW-JA", name: "Al Jahra" },
			{ code: "KW-HA", name: "Hawalli" },
			{ code: "KW-MU", name: "Mubarak Al-Kabeer" }
		]
	},
	{
		code: "KG",
		name: "Kyrgyzstan",
		currencyCode: "KGS",
		phoneCode: 996,
		provinces: []
	},
	{
		code: "LA",
		name: "Lao People's Democratic Republic",
		currencyCode: "LAK",
		phoneCode: 856,
		provinces: []
	},
	{
		code: "LV",
		name: "Latvia",
		currencyCode: "EUR",
		phoneCode: 371,
		provinces: []
	},
	{
		code: "LB",
		name: "Lebanon",
		currencyCode: "LBP",
		phoneCode: 961,
		provinces: []
	},
	{
		code: "LS",
		name: "Lesotho",
		currencyCode: "LSL",
		phoneCode: 266,
		provinces: []
	},
	{
		code: "LR",
		name: "Liberia",
		currencyCode: "LRD",
		phoneCode: 231,
		provinces: []
	},
	{
		code: "LY",
		name: "Libyan Arab Jamahiriya",
		currencyCode: "",
		phoneCode: 218,
		provinces: []
	},
	{
		code: "LI",
		name: "Liechtenstein",
		currencyCode: "CHF",
		phoneCode: 423,
		provinces: []
	},
	{
		code: "LT",
		name: "Lithuania",
		currencyCode: "EUR",
		phoneCode: 370,
		provinces: []
	},
	{
		code: "LU",
		name: "Luxembourg",
		currencyCode: "EUR",
		phoneCode: 352,
		provinces: []
	},
	{
		code: "MO",
		name: "Macao",
		currencyCode: "MOP",
		phoneCode: 853,
		provinces: []
	},
	{
		code: "MG",
		name: "Madagascar",
		currencyCode: "",
		phoneCode: 261,
		provinces: []
	},
	{
		code: "MW",
		name: "Malawi",
		currencyCode: "MWK",
		phoneCode: 265,
		provinces: []
	},
	{
		code: "MY",
		name: "Malaysia",
		currencyCode: "MYR",
		phoneCode: 60,
		provinces: [
			{ code: "JHR", name: "Johor" },
			{ code: "KDH", name: "Kedah" },
			{ code: "KTN", name: "Kelantan" },
			{ code: "KUL", name: "Kuala Lumpur" },
			{ code: "LBN", name: "Labuan" },
			{ code: "MLK", name: "Melaka" },
			{ code: "NSN", name: "Negeri Sembilan" },
			{ code: "PHG", name: "Pahang" },
			{ code: "PNG", name: "Penang" },
			{ code: "PRK", name: "Perak" },
			{ code: "PLS", name: "Perlis" },
			{ code: "PJY", name: "Putrajaya" },
			{ code: "SBH", name: "Sabah" },
			{ code: "SWK", name: "Sarawak" },
			{ code: "SGR", name: "Selangor" },
			{ code: "TRG", name: "Terengganu" }
		]
	},
	{
		code: "MV",
		name: "Maldives",
		currencyCode: "MVR",
		phoneCode: 960,
		provinces: []
	},
	{
		code: "ML",
		name: "Mali",
		currencyCode: "XOF",
		phoneCode: 223,
		provinces: []
	},
	{
		code: "MT",
		name: "Malta",
		currencyCode: "EUR",
		phoneCode: 356,
		provinces: []
	},
	{
		code: "MQ",
		name: "Martinique",
		currencyCode: "EUR",
		phoneCode: 596,
		provinces: []
	},
	{
		code: "MR",
		name: "Mauritania",
		currencyCode: "",
		phoneCode: 222,
		provinces: []
	},
	{
		code: "MU",
		name: "Mauritius",
		currencyCode: "MUR",
		phoneCode: 230,
		provinces: []
	},
	{
		code: "YT",
		name: "Mayotte",
		currencyCode: "EUR",
		phoneCode: 262,
		provinces: []
	},
	{
		code: "MX",
		name: "Mexico",
		currencyCode: "MXN",
		phoneCode: 52,
		provinces: [
			{ code: "AGS", name: "Aguascalientes" },
			{ code: "BC", name: "Baja California" },
			{ code: "BCS", name: "Baja California Sur" },
			{ code: "CAMP", name: "Campeche" },
			{ code: "CHIS", name: "Chiapas" },
			{ code: "CHIH", name: "Chihuahua" },
			{ code: "DF", name: "Ciudad de México" },
			{ code: "COAH", name: "Coahuila" },
			{ code: "COL", name: "Colima" },
			{ code: "DGO", name: "Durango" },
			{ code: "GTO", name: "Guanajuato" },
			{ code: "GRO", name: "Guerrero" },
			{ code: "HGO", name: "Hidalgo" },
			{ code: "JAL", name: "Jalisco" },
			{ code: "MEX", name: "México" },
			{ code: "MICH", name: "Michoacán" },
			{ code: "MOR", name: "Morelos" },
			{ code: "NAY", name: "Nayarit" },
			{ code: "NL", name: "Nuevo León" },
			{ code: "OAX", name: "Oaxaca" },
			{ code: "PUE", name: "Puebla" },
			{ code: "QRO", name: "Querétaro" },
			{ code: "Q ROO", name: "Quintana Roo" },
			{ code: "SLP", name: "San Luis Potosí" },
			{ code: "SIN", name: "Sinaloa" },
			{ code: "SON", name: "Sonora" },
			{ code: "TAB", name: "Tabasco" },
			{ code: "TAMPS", name: "Tamaulipas" },
			{ code: "TLAX", name: "Tlaxcala" },
			{ code: "VER", name: "Veracruz" },
			{ code: "YUC", name: "Yucatán" },
			{ code: "ZAC", name: "Zacatecas" }
		]
	},
	{
		code: "MD",
		name: "Moldova, Republic of",
		currencyCode: "MDL",
		phoneCode: 373,
		provinces: []
	},
	{
		code: "MC",
		name: "Monaco",
		currencyCode: "EUR",
		phoneCode: 377,
		provinces: []
	},
	{
		code: "MN",
		name: "Mongolia",
		currencyCode: "MNT",
		phoneCode: 976,
		provinces: []
	},
	{
		code: "ME",
		name: "Montenegro",
		currencyCode: "EUR",
		phoneCode: 382,
		provinces: []
	},
	{
		code: "MS",
		name: "Montserrat",
		currencyCode: "XCD",
		phoneCode: 1664,
		provinces: []
	},
	{
		code: "MA",
		name: "Morocco",
		currencyCode: "MAD",
		phoneCode: 212,
		provinces: []
	},
	{
		code: "MZ",
		name: "Mozambique",
		currencyCode: "MZN",
		phoneCode: 258,
		provinces: []
	},
	{
		code: "MM",
		name: "Myanmar",
		currencyCode: "MMK",
		phoneCode: 95,
		provinces: []
	},
	{
		code: "NA",
		name: "Namibia",
		currencyCode: "NAD",
		phoneCode: 264,
		provinces: []
	},
	{
		code: "NR",
		name: "Nauru",
		currencyCode: "AUD",
		phoneCode: 674,
		provinces: []
	},
	{
		code: "NP",
		name: "Nepal",
		currencyCode: "NPR",
		phoneCode: 977,
		provinces: []
	},
	{
		code: "NL",
		name: "Netherlands",
		currencyCode: "EUR",
		phoneCode: 31,
		provinces: []
	},
	{
		code: "NC",
		name: "New Caledonia",
		currencyCode: "XPF",
		phoneCode: 687,
		provinces: []
	},
	{
		code: "NZ",
		name: "New Zealand",
		currencyCode: "NZD",
		phoneCode: 64,
		provinces: [
			{ code: "AUK", name: "Auckland" },
			{ code: "BOP", name: "Bay of Plenty" },
			{ code: "CAN", name: "Canterbury" },
			{ code: "CIT", name: "Chatham Islands" },
			{ code: "GIS", name: "Gisborne" },
			{ code: "HKB", name: "Hawke's Bay" },
			{ code: "MWT", name: "Manawatu-Wanganui" },
			{ code: "MBH", name: "Marlborough" },
			{ code: "NSN", name: "Nelson" },
			{ code: "NTL", name: "Northland" },
			{ code: "OTA", name: "Otago" },
			{ code: "STL", name: "Southland" },
			{ code: "TKI", name: "Taranaki" },
			{ code: "TAS", name: "Tasman" },
			{ code: "WKO", name: "Waikato" },
			{ code: "WGN", name: "Wellington" },
			{ code: "WTC", name: "West Coast" }
		]
	},
	{
		code: "NI",
		name: "Nicaragua",
		currencyCode: "NIO",
		phoneCode: 505,
		provinces: []
	},
	{
		code: "NE",
		name: "Niger",
		currencyCode: "XOF",
		phoneCode: 227,
		provinces: []
	},
	{
		code: "NG",
		name: "Nigeria",
		currencyCode: "NGN",
		phoneCode: 234,
		provinces: [
			{ code: "AB", name: "Abia" },
			{ code: "FC", name: "Abuja Federal Capital Territory" },
			{ code: "AD", name: "Adamawa" },
			{ code: "AK", name: "Akwa Ibom" },
			{ code: "AN", name: "Anambra" },
			{ code: "BA", name: "Bauchi" },
			{ code: "BY", name: "Bayelsa" },
			{ code: "BE", name: "Benue" },
			{ code: "BO", name: "Borno" },
			{ code: "CR", name: "Cross River" },
			{ code: "DE", name: "Delta" },
			{ code: "EB", name: "Ebonyi" },
			{ code: "ED", name: "Edo" },
			{ code: "EK", name: "Ekiti" },
			{ code: "EN", name: "Enugu" },
			{ code: "GO", name: "Gombe" },
			{ code: "IM", name: "Imo" },
			{ code: "JI", name: "Jigawa" },
			{ code: "KD", name: "Kaduna" },
			{ code: "KN", name: "Kano" },
			{ code: "KT", name: "Katsina" },
			{ code: "KE", name: "Kebbi" },
			{ code: "KO", name: "Kogi" },
			{ code: "KW", name: "Kwara" },
			{ code: "LA", name: "Lagos" },
			{ code: "NA", name: "Nasarawa" },
			{ code: "NI", name: "Niger" },
			{ code: "OG", name: "Ogun" },
			{ code: "ON", name: "Ondo" },
			{ code: "OS", name: "Osun" },
			{ code: "OY", name: "Oyo" },
			{ code: "PL", name: "Plateau" },
			{ code: "RI", name: "Rivers" },
			{ code: "SO", name: "Sokoto" },
			{ code: "TA", name: "Taraba" },
			{ code: "YO", name: "Yobe" },
			{ code: "ZA", name: "Zamfara" }
		]
	},
	{
		code: "NU",
		name: "Niue",
		currencyCode: "NZD",
		phoneCode: 683,
		provinces: []
	},
	{
		code: "NF",
		name: "Norfolk Island",
		currencyCode: "AUD",
		phoneCode: 672,
		provinces: []
	},
	{
		code: "MK",
		name: "North Macedonia",
		currencyCode: "MKD",
		phoneCode: 389,
		provinces: []
	},
	{
		code: "NO",
		name: "Norway",
		currencyCode: "NOK",
		phoneCode: 47,
		provinces: []
	},
	{
		code: "OM",
		name: "Oman",
		currencyCode: "",
		phoneCode: 968,
		provinces: []
	},
	{
		code: "PK",
		name: "Pakistan",
		currencyCode: "PKR",
		phoneCode: 92,
		provinces: []
	},
	{
		code: "PS",
		name: "Palestinian Territory, Occupied",
		currencyCode: "ILS",
		phoneCode: 970,
		provinces: []
	},
	{
		code: "PA",
		name: "Panama",
		currencyCode: "USD",
		phoneCode: 507,
		provinces: [
			{ code: "PA-1", name: "Bocas del Toro" },
			{ code: "PA-4", name: "Chiriquí" },
			{ code: "PA-2", name: "Coclé" },
			{ code: "PA-3", name: "Colón" },
			{ code: "PA-5", name: "Darién" },
			{ code: "PA-EM", name: "Emberá" },
			{ code: "PA-6", name: "Herrera" },
			{ code: "PA-KY", name: "Kuna Yala" },
			{ code: "PA-7", name: "Los Santos" },
			{ code: "PA-NB", name: "Ngöbe-Buglé" },
			{ code: "PA-8", name: "Panamá" },
			{ code: "PA-10", name: "Panamá Oeste" },
			{ code: "PA-9", name: "Veraguas" }
		]
	},
	{
		code: "PG",
		name: "Papua New Guinea",
		currencyCode: "PGK",
		phoneCode: 675,
		provinces: []
	},
	{
		code: "PY",
		name: "Paraguay",
		currencyCode: "PYG",
		phoneCode: 595,
		provinces: []
	},
	{
		code: "PE",
		name: "Peru",
		currencyCode: "PEN",
		phoneCode: 51,
		provinces: [
			{ code: "PE-AMA", name: "Amazonas" },
			{ code: "PE-ANC", name: "Áncash" },
			{ code: "PE-APU", name: "Apurímac" },
			{ code: "PE-ARE", name: "Arequipa" },
			{ code: "PE-AYA", name: "Ayacucho" },
			{ code: "PE-CAJ", name: "Cajamarca" },
			{ code: "PE-CAL", name: "Callao" },
			{ code: "PE-CUS", name: "Cuzco" },
			{ code: "PE-HUV", name: "Huancavelica" },
			{ code: "PE-HUC", name: "Huánuco" },
			{ code: "PE-ICA", name: "Ica" },
			{ code: "PE-JUN", name: "Junín" },
			{ code: "PE-LAL", name: "La Libertad" },
			{ code: "PE-LAM", name: "Lambayeque" },
			{ code: "PE-LIM", name: "Lima (departamento)" },
			{ code: "PE-LMA", name: "Lima (provincia)" },
			{ code: "PE-LOR", name: "Loreto" },
			{ code: "PE-MDD", name: "Madre de Dios" },
			{ code: "PE-MOQ", name: "Moquegua" },
			{ code: "PE-PAS", name: "Pasco" },
			{ code: "PE-PIU", name: "Piura" },
			{ code: "PE-PUN", name: "Puno" },
			{ code: "PE-SAM", name: "San Martín" },
			{ code: "PE-TAC", name: "Tacna" },
			{ code: "PE-TUM", name: "Tumbes" },
			{ code: "PE-UCA", name: "Ucayali" }
		]
	},
	{
		code: "PH",
		name: "Philippines",
		currencyCode: "PHP",
		phoneCode: 63,
		provinces: [
			{ code: "PH-ABR", name: "Abra" },
			{ code: "PH-AGN", name: "Agusan del Norte" },
			{ code: "PH-AGS", name: "Agusan del Sur" },
			{ code: "PH-AKL", name: "Aklan" },
			{ code: "PH-ALB", name: "Albay" },
			{ code: "PH-ANT", name: "Antique" },
			{ code: "PH-APA", name: "Apayao" },
			{ code: "PH-AUR", name: "Aurora" },
			{ code: "PH-BAS", name: "Basilan" },
			{ code: "PH-BAN", name: "Bataan" },
			{ code: "PH-BTN", name: "Batanes" },
			{ code: "PH-BTG", name: "Batangas" },
			{ code: "PH-BEN", name: "Benguet" },
			{ code: "PH-BIL", name: "Biliran" },
			{ code: "PH-BOH", name: "Bohol" },
			{ code: "PH-BUK", name: "Bukidnon" },
			{ code: "PH-BUL", name: "Bulacan" },
			{ code: "PH-CAG", name: "Cagayan" },
			{ code: "PH-CAN", name: "Camarines Norte" },
			{ code: "PH-CAS", name: "Camarines Sur" },
			{ code: "PH-CAM", name: "Camiguin" },
			{ code: "PH-CAP", name: "Capiz" },
			{ code: "PH-CAT", name: "Catanduanes" },
			{ code: "PH-CAV", name: "Cavite" },
			{ code: "PH-CEB", name: "Cebu" },
			{ code: "PH-NCO", name: "Cotabato" },
			{ code: "PH-COM", name: "Davao de Oro" },
			{ code: "PH-DAV", name: "Davao del Norte" },
			{ code: "PH-DAS", name: "Davao del Sur" },
			{ code: "PH-DVO", name: "Davao Occidental" },
			{ code: "PH-DAO", name: "Davao Oriental" },
			{ code: "PH-DIN", name: "Dinagat Islands" },
			{ code: "PH-EAS", name: "Eastern Samar" },
			{ code: "PH-GUI", name: "Guimaras" },
			{ code: "PH-IFU", name: "Ifugao" },
			{ code: "PH-ILN", name: "Ilocos Norte" },
			{ code: "PH-ILS", name: "Ilocos Sur" },
			{ code: "PH-ILI", name: "Iloilo" },
			{ code: "PH-ISA", name: "Isabela" },
			{ code: "PH-KAL", name: "Kalinga" },
			{ code: "PH-LUN", name: "La Union" },
			{ code: "PH-LAG", name: "Laguna" },
			{ code: "PH-LAN", name: "Lanao del Norte" },
			{ code: "PH-LAS", name: "Lanao del Sur" },
			{ code: "PH-LEY", name: "Leyte" },
			{ code: "PH-MAG", name: "Maguindanao" },
			{ code: "PH-MAD", name: "Marinduque" },
			{ code: "PH-MAS", name: "Masbate" },
			{ code: "PH-00", name: "Metro Manila" },
			{ code: "PH-MSC", name: "Misamis Occidental" },
			{ code: "PH-MSR", name: "Misamis Oriental" },
			{ code: "PH-MOU", name: "Mountain Province" },
			{ code: "PH-NEC", name: "Negros Occidental" },
			{ code: "PH-NER", name: "Negros Oriental" },
			{ code: "PH-NSA", name: "Northern Samar" },
			{ code: "PH-NUE", name: "Nueva Ecija" },
			{ code: "PH-NUV", name: "Nueva Vizcaya" },
			{ code: "PH-MDC", name: "Occidental Mindoro" },
			{ code: "PH-MDR", name: "Oriental Mindoro" },
			{ code: "PH-PLW", name: "Palawan" },
			{ code: "PH-PAM", name: "Pampanga" },
			{ code: "PH-PAN", name: "Pangasinan" },
			{ code: "PH-QUE", name: "Quezon" },
			{ code: "PH-QUI", name: "Quirino" },
			{ code: "PH-RIZ", name: "Rizal" },
			{ code: "PH-ROM", name: "Romblon" },
			{ code: "PH-WSA", name: "Samar" },
			{ code: "PH-SAR", name: "Sarangani" },
			{ code: "PH-SIG", name: "Siquijor" },
			{ code: "PH-SOR", name: "Sorsogon" },
			{ code: "PH-SCO", name: "South Cotabato" },
			{ code: "PH-SLE", name: "Southern Leyte" },
			{ code: "PH-SUK", name: "Sultan Kudarat" },
			{ code: "PH-SLU", name: "Sulu" },
			{ code: "PH-SUN", name: "Surigao del Norte" },
			{ code: "PH-SUR", name: "Surigao del Sur" },
			{ code: "PH-TAR", name: "Tarlac" },
			{ code: "PH-TAW", name: "Tawi-Tawi" },
			{ code: "PH-ZMB", name: "Zambales" },
			{ code: "PH-ZAN", name: "Zamboanga del Norte" },
			{ code: "PH-ZAS", name: "Zamboanga del Sur" },
			{ code: "PH-ZSI", name: "Zamboanga Sibugay" }
		]
	},
	{
		code: "PN",
		name: "Pitcairn",
		currencyCode: "NZD",
		phoneCode: 64,
		provinces: []
	},
	{
		code: "PL",
		name: "Poland",
		currencyCode: "PLN",
		phoneCode: 48,
		provinces: []
	},
	{
		code: "PT",
		name: "Portugal",
		currencyCode: "EUR",
		phoneCode: 351,
		provinces: [
			{ code: "PT-20", name: "Açores" },
			{ code: "PT-01", name: "Aveiro" },
			{ code: "PT-02", name: "Beja" },
			{ code: "PT-03", name: "Braga" },
			{ code: "PT-04", name: "Bragança" },
			{ code: "PT-05", name: "Castelo Branco" },
			{ code: "PT-06", name: "Coimbra" },
			{ code: "PT-07", name: "Évora" },
			{ code: "PT-08", name: "Faro" },
			{ code: "PT-09", name: "Guarda" },
			{ code: "PT-10", name: "Leiria" },
			{ code: "PT-11", name: "Lisboa" },
			{ code: "PT-30", name: "Madeira" },
			{ code: "PT-12", name: "Portalegre" },
			{ code: "PT-13", name: "Porto" },
			{ code: "PT-14", name: "Santarém" },
			{ code: "PT-15", name: "Setúbal" },
			{ code: "PT-16", name: "Viana do Castelo" },
			{ code: "PT-17", name: "Vila Real" },
			{ code: "PT-18", name: "Viseu" }
		]
	},
	{
		code: "QA",
		name: "Qatar",
		currencyCode: "QAR",
		phoneCode: 974,
		provinces: []
	},
	{
		code: "CM",
		name: "Republic of Cameroon",
		currencyCode: "XAF",
		phoneCode: 237,
		provinces: []
	},
	{
		code: "RE",
		name: "Reunion",
		currencyCode: "EUR",
		phoneCode: 262,
		provinces: []
	},
	{
		code: "RO",
		name: "Romania",
		currencyCode: "RON",
		phoneCode: 40,
		provinces: [
			{ code: "AB", name: "Alba" },
			{ code: "AR", name: "Arad" },
			{ code: "AG", name: "Argeș" },
			{ code: "BC", name: "Bacău" },
			{ code: "BH", name: "Bihor" },
			{ code: "BN", name: "Bistrița-Năsăud" },
			{ code: "BT", name: "Botoșani" },
			{ code: "BR", name: "Brăila" },
			{ code: "BV", name: "Brașov" },
			{ code: "B", name: "București" },
			{ code: "BZ", name: "Buzău" },
			{ code: "CL", name: "Călărași" },
			{ code: "CS", name: "Caraș-Severin" },
			{ code: "CJ", name: "Cluj" },
			{ code: "CT", name: "Constanța" },
			{ code: "CV", name: "Covasna" },
			{ code: "DB", name: "Dâmbovița" },
			{ code: "DJ", name: "Dolj" },
			{ code: "GL", name: "Galați" },
			{ code: "GR", name: "Giurgiu" },
			{ code: "GJ", name: "Gorj" },
			{ code: "HR", name: "Harghita" },
			{ code: "HD", name: "Hunedoara" },
			{ code: "IL", name: "Ialomița" },
			{ code: "IS", name: "Iași" },
			{ code: "IF", name: "Ilfov" },
			{ code: "MM", name: "Maramureș" },
			{ code: "MH", name: "Mehedinți" },
			{ code: "MS", name: "Mureș" },
			{ code: "NT", name: "Neamț" },
			{ code: "OT", name: "Olt" },
			{ code: "PH", name: "Prahova" },
			{ code: "SJ", name: "Sălaj" },
			{ code: "SM", name: "Satu Mare" },
			{ code: "SB", name: "Sibiu" },
			{ code: "SV", name: "Suceava" },
			{ code: "TR", name: "Teleorman" },
			{ code: "TM", name: "Timiș" },
			{ code: "TL", name: "Tulcea" },
			{ code: "VL", name: "Vâlcea" },
			{ code: "VS", name: "Vaslui" },
			{ code: "VN", name: "Vrancea" }
		]
	},
	{
		code: "RU",
		name: "Russia",
		currencyCode: "RUB",
		phoneCode: 7,
		provinces: [
			{ code: "ALT", name: "Altai Krai" },
			{ code: "AL", name: "Altai Republic" },
			{ code: "AMU", name: "Amur Oblast" },
			{ code: "ARK", name: "Arkhangelsk Oblast" },
			{ code: "AST", name: "Astrakhan Oblast" },
			{ code: "BEL", name: "Belgorod Oblast" },
			{ code: "BRY", name: "Bryansk Oblast" },
			{ code: "CE", name: "Chechen Republic" },
			{ code: "CHE", name: "Chelyabinsk Oblast" },
			{ code: "CHU", name: "Chukotka Autonomous Okrug" },
			{ code: "CU", name: "Chuvash Republic" },
			{ code: "IRK", name: "Irkutsk Oblast" },
			{ code: "IVA", name: "Ivanovo Oblast" },
			{ code: "YEV", name: "Jewish Autonomous Oblast" },
			{ code: "KB", name: "Kabardino-Balkarian Republic" },
			{ code: "KGD", name: "Kaliningrad Oblast" },
			{ code: "KLU", name: "Kaluga Oblast" },
			{ code: "KAM", name: "Kamchatka Krai" },
			{ code: "KC", name: "Karachay–Cherkess Republic" },
			{ code: "KEM", name: "Kemerovo Oblast" },
			{ code: "KHA", name: "Khabarovsk Krai" },
			{ code: "KHM", name: "Khanty-Mansi Autonomous Okrug" },
			{ code: "KIR", name: "Kirov Oblast" },
			{ code: "KO", name: "Komi Republic" },
			{ code: "KOS", name: "Kostroma Oblast" },
			{ code: "KDA", name: "Krasnodar Krai" },
			{ code: "KYA", name: "Krasnoyarsk Krai" },
			{ code: "KGN", name: "Kurgan Oblast" },
			{ code: "KRS", name: "Kursk Oblast" },
			{ code: "LEN", name: "Leningrad Oblast" },
			{ code: "LIP", name: "Lipetsk Oblast" },
			{ code: "MAG", name: "Magadan Oblast" },
			{ code: "ME", name: "Mari El Republic" },
			{ code: "MOW", name: "Moscow" },
			{ code: "MOS", name: "Moscow Oblast" },
			{ code: "MUR", name: "Murmansk Oblast" },
			{ code: "NIZ", name: "Nizhny Novgorod Oblast" },
			{ code: "NGR", name: "Novgorod Oblast" },
			{ code: "NVS", name: "Novosibirsk Oblast" },
			{ code: "OMS", name: "Omsk Oblast" },
			{ code: "ORE", name: "Orenburg Oblast" },
			{ code: "ORL", name: "Oryol Oblast" },
			{ code: "PNZ", name: "Penza Oblast" },
			{ code: "PER", name: "Perm Krai" },
			{ code: "PRI", name: "Primorsky Krai" },
			{ code: "PSK", name: "Pskov Oblast" },
			{ code: "AD", name: "Republic of Adygeya" },
			{ code: "BA", name: "Republic of Bashkortostan" },
			{ code: "BU", name: "Republic of Buryatia" },
			{ code: "DA", name: "Republic of Dagestan" },
			{ code: "IN", name: "Republic of Ingushetia" },
			{ code: "KL", name: "Republic of Kalmykia" },
			{ code: "KR", name: "Republic of Karelia" },
			{ code: "KK", name: "Republic of Khakassia" },
			{ code: "MO", name: "Republic of Mordovia" },
			{ code: "SE", name: "Republic of North Ossetia–Alania" },
			{ code: "TA", name: "Republic of Tatarstan" },
			{ code: "ROS", name: "Rostov Oblast" },
			{ code: "RYA", name: "Ryazan Oblast" },
			{ code: "SPE", name: "Saint Petersburg" },
			{ code: "SA", name: "Sakha Republic (Yakutia)" },
			{ code: "SAK", name: "Sakhalin Oblast" },
			{ code: "SAM", name: "Samara Oblast" },
			{ code: "SAR", name: "Saratov Oblast" },
			{ code: "SMO", name: "Smolensk Oblast" },
			{ code: "STA", name: "Stavropol Krai" },
			{ code: "SVE", name: "Sverdlovsk Oblast" },
			{ code: "TAM", name: "Tambov Oblast" },
			{ code: "TOM", name: "Tomsk Oblast" },
			{ code: "TUL", name: "Tula Oblast" },
			{ code: "TVE", name: "Tver Oblast" },
			{ code: "TYU", name: "Tyumen Oblast" },
			{ code: "TY", name: "Tyva Republic" },
			{ code: "UD", name: "Udmurtia" },
			{ code: "ULY", name: "Ulyanovsk Oblast" },
			{ code: "VLA", name: "Vladimir Oblast" },
			{ code: "VGG", name: "Volgograd Oblast" },
			{ code: "VLG", name: "Vologda Oblast" },
			{ code: "VOR", name: "Voronezh Oblast" },
			{ code: "YAN", name: "Yamalo-Nenets Autonomous Okrug" },
			{ code: "YAR", name: "Yaroslavl Oblast" },
			{ code: "ZAB", name: "Zabaykalsky Krai" }
		]
	},
	{
		code: "RW",
		name: "Rwanda",
		currencyCode: "RWF",
		phoneCode: 250,
		provinces: []
	},
	{
		code: "BL",
		name: "Saint Barthélemy",
		currencyCode: "EUR",
		phoneCode: 590,
		provinces: []
	},
	{
		code: "SH",
		name: "Saint Helena",
		currencyCode: "SHP",
		phoneCode: 2,
		provinces: []
	},
	{
		code: "KN",
		name: "Saint Kitts And Nevis",
		currencyCode: "XCD",
		phoneCode: 1869,
		provinces: []
	},
	{
		code: "LC",
		name: "Saint Lucia",
		currencyCode: "XCD",
		phoneCode: 1758,
		provinces: []
	},
	{
		code: "MF",
		name: "Saint Martin",
		currencyCode: "EUR",
		phoneCode: 590,
		provinces: []
	},
	{
		code: "PM",
		name: "Saint Pierre And Miquelon",
		currencyCode: "EUR",
		phoneCode: 508,
		provinces: []
	},
	{
		code: "WS",
		name: "Samoa",
		currencyCode: "WST",
		phoneCode: 685,
		provinces: []
	},
	{
		code: "SM",
		name: "San Marino",
		currencyCode: "EUR",
		phoneCode: 378,
		provinces: []
	},
	{
		code: "ST",
		name: "Sao Tome And Principe",
		currencyCode: "STD",
		phoneCode: 239,
		provinces: []
	},
	{
		code: "SA",
		name: "Saudi Arabia",
		currencyCode: "SAR",
		phoneCode: 966,
		provinces: []
	},
	{
		code: "SN",
		name: "Senegal",
		currencyCode: "XOF",
		phoneCode: 221,
		provinces: []
	},
	{
		code: "RS",
		name: "Serbia",
		currencyCode: "RSD",
		phoneCode: 381,
		provinces: []
	},
	{
		code: "SC",
		name: "Seychelles",
		currencyCode: "SCR",
		phoneCode: 248,
		provinces: []
	},
	{
		code: "SL",
		name: "Sierra Leone",
		currencyCode: "SLL",
		phoneCode: 232,
		provinces: []
	},
	{
		code: "SG",
		name: "Singapore",
		currencyCode: "SGD",
		phoneCode: 65,
		provinces: []
	},
	{
		code: "SX",
		name: "Sint Maarten",
		currencyCode: "ANG",
		phoneCode: 1721,
		provinces: []
	},
	{
		code: "SK",
		name: "Slovakia",
		currencyCode: "EUR",
		phoneCode: 421,
		provinces: []
	},
	{
		code: "SI",
		name: "Slovenia",
		currencyCode: "EUR",
		phoneCode: 386,
		provinces: []
	},
	{
		code: "SB",
		name: "Solomon Islands",
		currencyCode: "SBD",
		phoneCode: 677,
		provinces: []
	},
	{
		code: "SO",
		name: "Somalia",
		currencyCode: "",
		phoneCode: 252,
		provinces: []
	},
	{
		code: "ZA",
		name: "South Africa",
		currencyCode: "ZAR",
		phoneCode: 27,
		provinces: [
			{ code: "EC", name: "Eastern Cape" },
			{ code: "FS", name: "Free State" },
			{ code: "GP", name: "Gauteng" },
			{ code: "NL", name: "KwaZulu-Natal" },
			{ code: "LP", name: "Limpopo" },
			{ code: "MP", name: "Mpumalanga" },
			{ code: "NW", name: "North West" },
			{ code: "NC", name: "Northern Cape" },
			{ code: "WC", name: "Western Cape" }
		]
	},
	{
		code: "GS",
		name: "South Georgia And The South Sandwich Islands",
		currencyCode: "GBP",
		phoneCode: 500,
		provinces: []
	},
	{
		code: "KR",
		name: "South Korea",
		currencyCode: "KRW",
		phoneCode: 82,
		provinces: [
			{ code: "KR-26", name: "Busan" },
			{ code: "KR-43", name: "Chungbuk" },
			{ code: "KR-44", name: "Chungnam" },
			{ code: "KR-27", name: "Daegu" },
			{ code: "KR-30", name: "Daejeon" },
			{ code: "KR-42", name: "Gangwon" },
			{ code: "KR-29", name: "Gwangju" },
			{ code: "KR-47", name: "Gyeongbuk" },
			{ code: "KR-41", name: "Gyeonggi" },
			{ code: "KR-48", name: "Gyeongnam" },
			{ code: "KR-28", name: "Incheon" },
			{ code: "KR-49", name: "Jeju" },
			{ code: "KR-45", name: "Jeonbuk" },
			{ code: "KR-46", name: "Jeonnam" },
			{ code: "KR-50", name: "Sejong" },
			{ code: "KR-11", name: "Seoul" },
			{ code: "KR-31", name: "Ulsan" }
		]
	},
	{
		code: "SS",
		name: "South Sudan",
		currencyCode: "",
		phoneCode: 211,
		provinces: []
	},
	{
		code: "ES",
		name: "Spain",
		currencyCode: "EUR",
		phoneCode: 34,
		provinces: [
			{ code: "C", name: "A Coruña" },
			{ code: "VI", name: "Álava" },
			{ code: "AB", name: "Albacete" },
			{ code: "A", name: "Alicante" },
			{ code: "AL", name: "Almería" },
			{ code: "O", name: "Asturias" },
			{ code: "AV", name: "Ávila" },
			{ code: "BA", name: "Badajoz" },
			{ code: "PM", name: "Balears" },
			{ code: "B", name: "Barcelona" },
			{ code: "BU", name: "Burgos" },
			{ code: "CC", name: "Cáceres" },
			{ code: "CA", name: "Cádiz" },
			{ code: "S", name: "Cantabria" },
			{ code: "CS", name: "Castellón" },
			{ code: "CE", name: "Ceuta" },
			{ code: "CR", name: "Ciudad Real" },
			{ code: "CO", name: "Córdoba" },
			{ code: "CU", name: "Cuenca" },
			{ code: "GI", name: "Girona" },
			{ code: "GR", name: "Granada" },
			{ code: "GU", name: "Guadalajara" },
			{ code: "SS", name: "Guipúzcoa" },
			{ code: "H", name: "Huelva" },
			{ code: "HU", name: "Huesca" },
			{ code: "J", name: "Jaén" },
			{ code: "LO", name: "La Rioja" },
			{ code: "GC", name: "Las Palmas" },
			{ code: "LE", name: "León" },
			{ code: "L", name: "Lleida" },
			{ code: "LU", name: "Lugo" },
			{ code: "M", name: "Madrid" },
			{ code: "MA", name: "Málaga" },
			{ code: "ML", name: "Melilla" },
			{ code: "MU", name: "Murcia" },
			{ code: "NA", name: "Navarra" },
			{ code: "OR", name: "Ourense" },
			{ code: "P", name: "Palencia" },
			{ code: "PO", name: "Pontevedra" },
			{ code: "SA", name: "Salamanca" },
			{ code: "TF", name: "Santa Cruz de Tenerife" },
			{ code: "SG", name: "Segovia" },
			{ code: "SE", name: "Sevilla" },
			{ code: "SO", name: "Soria" },
			{ code: "T", name: "Tarragona" },
			{ code: "TE", name: "Teruel" },
			{ code: "TO", name: "Toledo" },
			{ code: "V", name: "Valencia" },
			{ code: "VA", name: "Valladolid" },
			{ code: "BI", name: "Vizcaya" },
			{ code: "ZA", name: "Zamora" },
			{ code: "Z", name: "Zaragoza" }
		]
	},
	{
		code: "LK",
		name: "Sri Lanka",
		currencyCode: "LKR",
		phoneCode: 94,
		provinces: []
	},
	{
		code: "VC",
		name: "St. Vincent",
		currencyCode: "XCD",
		phoneCode: 1784,
		provinces: []
	},
	{
		code: "SD",
		name: "Sudan",
		currencyCode: "",
		phoneCode: 249,
		provinces: []
	},
	{
		code: "SR",
		name: "Suriname",
		currencyCode: "SRD",
		phoneCode: 597,
		provinces: []
	},
	{
		code: "SJ",
		name: "Svalbard And Jan Mayen",
		currencyCode: "NOK",
		phoneCode: 4779,
		provinces: []
	},
	{
		code: "SE",
		name: "Sweden",
		currencyCode: "SEK",
		phoneCode: 46,
		provinces: []
	},
	{
		code: "CH",
		name: "Switzerland",
		currencyCode: "CHF",
		phoneCode: 41,
		provinces: []
	},
	{
		code: "TW",
		name: "Taiwan",
		currencyCode: "TWD",
		phoneCode: 886,
		provinces: []
	},
	{
		code: "TJ",
		name: "Tajikistan",
		currencyCode: "TJS",
		phoneCode: 992,
		provinces: []
	},
	{
		code: "TZ",
		name: "Tanzania, United Republic Of",
		currencyCode: "TZS",
		phoneCode: 255,
		provinces: []
	},
	{
		code: "TH",
		name: "Thailand",
		currencyCode: "THB",
		phoneCode: 66,
		provinces: [
			{ code: "TH-37", name: "Amnat Charoen" },
			{ code: "TH-15", name: "Ang Thong" },
			{ code: "TH-10", name: "Bangkok" },
			{ code: "TH-38", name: "Bueng Kan" },
			{ code: "TH-31", name: "Buriram" },
			{ code: "TH-24", name: "Chachoengsao" },
			{ code: "TH-18", name: "Chai Nat" },
			{ code: "TH-36", name: "Chaiyaphum" },
			{ code: "TH-22", name: "Chanthaburi" },
			{ code: "TH-50", name: "Chiang Mai" },
			{ code: "TH-57", name: "Chiang Rai" },
			{ code: "TH-20", name: "Chon Buri" },
			{ code: "TH-86", name: "Chumphon" },
			{ code: "TH-46", name: "Kalasin" },
			{ code: "TH-62", name: "Kamphaeng Phet" },
			{ code: "TH-71", name: "Kanchanaburi" },
			{ code: "TH-40", name: "Khon Kaen" },
			{ code: "TH-81", name: "Krabi" },
			{ code: "TH-52", name: "Lampang" },
			{ code: "TH-51", name: "Lamphun" },
			{ code: "TH-42", name: "Loei" },
			{ code: "TH-16", name: "Lopburi" },
			{ code: "TH-58", name: "Mae Hong Son" },
			{ code: "TH-44", name: "Maha Sarakham" },
			{ code: "TH-49", name: "Mukdahan" },
			{ code: "TH-26", name: "Nakhon Nayok" },
			{ code: "TH-73", name: "Nakhon Pathom" },
			{ code: "TH-48", name: "Nakhon Phanom" },
			{ code: "TH-30", name: "Nakhon Ratchasima" },
			{ code: "TH-60", name: "Nakhon Sawan" },
			{ code: "TH-80", name: "Nakhon Si Thammarat" },
			{ code: "TH-55", name: "Nan" },
			{ code: "TH-96", name: "Narathiwat" },
			{ code: "TH-39", name: "Nong Bua Lam Phu" },
			{ code: "TH-43", name: "Nong Khai" },
			{ code: "TH-12", name: "Nonthaburi" },
			{ code: "TH-13", name: "Pathum Thani" },
			{ code: "TH-94", name: "Pattani" },
			{ code: "TH-S", name: "Pattaya" },
			{ code: "TH-82", name: "Phangnga" },
			{ code: "TH-93", name: "Phatthalung" },
			{ code: "TH-56", name: "Phayao" },
			{ code: "TH-67", name: "Phetchabun" },
			{ code: "TH-76", name: "Phetchaburi" },
			{ code: "TH-66", name: "Phichit" },
			{ code: "TH-65", name: "Phitsanulok" },
			{ code: "TH-14", name: "Phra Nakhon Si Ayutthaya" },
			{ code: "TH-54", name: "Phrae" },
			{ code: "TH-83", name: "Phuket" },
			{ code: "TH-25", name: "Prachin Buri" },
			{ code: "TH-77", name: "Prachuap Khiri Khan" },
			{ code: "TH-85", name: "Ranong" },
			{ code: "TH-70", name: "Ratchaburi" },
			{ code: "TH-21", name: "Rayong" },
			{ code: "TH-45", name: "Roi Et" },
			{ code: "TH-27", name: "Sa Kaeo" },
			{ code: "TH-47", name: "Sakon Nakhon" },
			{ code: "TH-11", name: "Samut Prakan" },
			{ code: "TH-74", name: "Samut Sakhon" },
			{ code: "TH-75", name: "Samut Songkhram" },
			{ code: "TH-19", name: "Saraburi" },
			{ code: "TH-91", name: "Satun" },
			{ code: "TH-17", name: "Sing Buri" },
			{ code: "TH-33", name: "Sisaket" },
			{ code: "TH-90", name: "Songkhla" },
			{ code: "TH-64", name: "Sukhothai" },
			{ code: "TH-72", name: "Suphan Buri" },
			{ code: "TH-84", name: "Surat Thani" },
			{ code: "TH-32", name: "Surin" },
			{ code: "TH-63", name: "Tak" },
			{ code: "TH-92", name: "Trang" },
			{ code: "TH-23", name: "Trat" },
			{ code: "TH-34", name: "Ubon Ratchathani" },
			{ code: "TH-41", name: "Udon Thani" },
			{ code: "TH-61", name: "Uthai Thani" },
			{ code: "TH-53", name: "Uttaradit" },
			{ code: "TH-95", name: "Yala" },
			{ code: "TH-35", name: "Yasothon" }
		]
	},
	{
		code: "TL",
		name: "Timor Leste",
		currencyCode: "USD",
		phoneCode: 670,
		provinces: []
	},
	{
		code: "TG",
		name: "Togo",
		currencyCode: "XOF",
		phoneCode: 228,
		provinces: []
	},
	{
		code: "TK",
		name: "Tokelau",
		currencyCode: "NZD",
		phoneCode: 690,
		provinces: []
	},
	{
		code: "TO",
		name: "Tonga",
		currencyCode: "TOP",
		phoneCode: 676,
		provinces: []
	},
	{
		code: "TT",
		name: "Trinidad and Tobago",
		currencyCode: "TTD",
		phoneCode: 1868,
		provinces: []
	},
	{
		code: "TA",
		name: "Tristan da Cunha",
		currencyCode: "GBP",
		phoneCode: 2908,
		provinces: []
	},
	{
		code: "TN",
		name: "Tunisia",
		currencyCode: "",
		phoneCode: 216,
		provinces: []
	},
	{
		code: "TR",
		name: "Turkey",
		currencyCode: "TRY",
		phoneCode: 90,
		provinces: []
	},
	{
		code: "TM",
		name: "Turkmenistan",
		currencyCode: "",
		phoneCode: 993,
		provinces: []
	},
	{
		code: "TC",
		name: "Turks and Caicos Islands",
		currencyCode: "USD",
		phoneCode: 1649,
		provinces: []
	},
	{
		code: "TV",
		name: "Tuvalu",
		currencyCode: "AUD",
		phoneCode: 688,
		provinces: []
	},
	{
		code: "UG",
		name: "Uganda",
		currencyCode: "UGX",
		phoneCode: 256,
		provinces: []
	},
	{
		code: "UA",
		name: "Ukraine",
		currencyCode: "UAH",
		phoneCode: 380,
		provinces: []
	},
	{
		code: "AE",
		name: "United Arab Emirates",
		currencyCode: "AED",
		phoneCode: 971,
		provinces: [
			{ code: "AZ", name: "Abu Dhabi" },
			{ code: "AJ", name: "Ajman" },
			{ code: "DU", name: "Dubai" },
			{ code: "FU", name: "Fujairah" },
			{ code: "RK", name: "Ras al-Khaimah" },
			{ code: "SH", name: "Sharjah" },
			{ code: "UQ", name: "Umm al-Quwain" }
		]
	},
	{
		code: "GB",
		name: "United Kingdom",
		currencyCode: "GBP",
		phoneCode: 44,
		provinces: [
			{ code: "BFP", name: "British Forces" },
			{ code: "ENG", name: "England" },
			{ code: "NIR", name: "Northern Ireland" },
			{ code: "SCT", name: "Scotland" },
			{ code: "WLS", name: "Wales" }
		]
	},
	{
		code: "US",
		name: "United States",
		currencyCode: "USD",
		phoneCode: 1,
		provinces: [
			{ code: "AL", name: "Alabama" },
			{ code: "AK", name: "Alaska" },
			{ code: "AS", name: "American Samoa" },
			{ code: "AZ", name: "Arizona" },
			{ code: "AR", name: "Arkansas" },
			{ code: "AA", name: "Armed Forces Americas" },
			{ code: "AE", name: "Armed Forces Europe" },
			{ code: "AP", name: "Armed Forces Pacific" },
			{ code: "CA", name: "California" },
			{ code: "CO", name: "Colorado" },
			{ code: "CT", name: "Connecticut" },
			{ code: "DE", name: "Delaware" },
			{ code: "DC", name: "District of Columbia" },
			{ code: "FM", name: "Federated States of Micronesia" },
			{ code: "FL", name: "Florida" },
			{ code: "GA", name: "Georgia" },
			{ code: "GU", name: "Guam" },
			{ code: "HI", name: "Hawaii" },
			{ code: "ID", name: "Idaho" },
			{ code: "IL", name: "Illinois" },
			{ code: "IN", name: "Indiana" },
			{ code: "IA", name: "Iowa" },
			{ code: "KS", name: "Kansas" },
			{ code: "KY", name: "Kentucky" },
			{ code: "LA", name: "Louisiana" },
			{ code: "ME", name: "Maine" },
			{ code: "MH", name: "Marshall Islands" },
			{ code: "MD", name: "Maryland" },
			{ code: "MA", name: "Massachusetts" },
			{ code: "MI", name: "Michigan" },
			{ code: "MN", name: "Minnesota" },
			{ code: "MS", name: "Mississippi" },
			{ code: "MO", name: "Missouri" },
			{ code: "MT", name: "Montana" },
			{ code: "NE", name: "Nebraska" },
			{ code: "NV", name: "Nevada" },
			{ code: "NH", name: "New Hampshire" },
			{ code: "NJ", name: "New Jersey" },
			{ code: "NM", name: "New Mexico" },
			{ code: "NY", name: "New York" },
			{ code: "NC", name: "North Carolina" },
			{ code: "ND", name: "North Dakota" },
			{ code: "MP", name: "Northern Mariana Islands" },
			{ code: "OH", name: "Ohio" },
			{ code: "OK", name: "Oklahoma" },
			{ code: "OR", name: "Oregon" },
			{ code: "PW", name: "Palau" },
			{ code: "PA", name: "Pennsylvania" },
			{ code: "PR", name: "Puerto Rico" },
			{ code: "RI", name: "Rhode Island" },
			{ code: "SC", name: "South Carolina" },
			{ code: "SD", name: "South Dakota" },
			{ code: "TN", name: "Tennessee" },
			{ code: "TX", name: "Texas" },
			{ code: "UT", name: "Utah" },
			{ code: "VT", name: "Vermont" },
			{ code: "VI", name: "Virgin Islands" },
			{ code: "VA", name: "Virginia" },
			{ code: "WA", name: "Washington" },
			{ code: "WV", name: "West Virginia" },
			{ code: "WI", name: "Wisconsin" },
			{ code: "WY", name: "Wyoming" }
		]
	},
	{
		code: "UM",
		name: "United States Minor Outlying Islands",
		currencyCode: "USD",
		phoneCode: 268,
		provinces: []
	},
	{
		code: "UY",
		name: "Uruguay",
		currencyCode: "UYU",
		phoneCode: 598,
		provinces: [
			{ code: "UY-AR", name: "Artigas" },
			{ code: "UY-CA", name: "Canelones" },
			{ code: "UY-CL", name: "Cerro Largo" },
			{ code: "UY-CO", name: "Colonia" },
			{ code: "UY-DU", name: "Durazno" },
			{ code: "UY-FS", name: "Flores" },
			{ code: "UY-FD", name: "Florida" },
			{ code: "UY-LA", name: "Lavalleja" },
			{ code: "UY-MA", name: "Maldonado" },
			{ code: "UY-MO", name: "Montevideo" },
			{ code: "UY-PA", name: "Paysandú" },
			{ code: "UY-RN", name: "Río Negro" },
			{ code: "UY-RV", name: "Rivera" },
			{ code: "UY-RO", name: "Rocha" },
			{ code: "UY-SA", name: "Salto" },
			{ code: "UY-SJ", name: "San José" },
			{ code: "UY-SO", name: "Soriano" },
			{ code: "UY-TA", name: "Tacuarembó" },
			{ code: "UY-TT", name: "Treinta y Tres" }
		]
	},
	{
		code: "UZ",
		name: "Uzbekistan",
		currencyCode: "UZS",
		phoneCode: 998,
		provinces: []
	},
	{
		code: "VU",
		name: "Vanuatu",
		currencyCode: "VUV",
		phoneCode: 678,
		provinces: []
	},
	{
		code: "VE",
		name: "Venezuela",
		currencyCode: "USD",
		phoneCode: 58,
		provinces: [
			{ code: "VE-Z", name: "Amazonas" },
			{ code: "VE-B", name: "Anzoátegui" },
			{ code: "VE-C", name: "Apure" },
			{ code: "VE-D", name: "Aragua" },
			{ code: "VE-E", name: "Barinas" },
			{ code: "VE-F", name: "Bolívar" },
			{ code: "VE-G", name: "Carabobo" },
			{ code: "VE-H", name: "Cojedes" },
			{ code: "VE-Y", name: "Delta Amacuro" },
			{ code: "VE-W", name: "Dependencias Federales" },
			{ code: "VE-A", name: "Distrito Capital" },
			{ code: "VE-I", name: "Falcón" },
			{ code: "VE-J", name: "Guárico" },
			{ code: "VE-X", name: "La Guaira" },
			{ code: "VE-K", name: "Lara" },
			{ code: "VE-L", name: "Mérida" },
			{ code: "VE-M", name: "Miranda" },
			{ code: "VE-N", name: "Monagas" },
			{ code: "VE-O", name: "Nueva Esparta" },
			{ code: "VE-P", name: "Portuguesa" },
			{ code: "VE-R", name: "Sucre" },
			{ code: "VE-S", name: "Táchira" },
			{ code: "VE-T", name: "Trujillo" },
			{ code: "VE-U", name: "Yaracuy" },
			{ code: "VE-V", name: "Zulia" }
		]
	},
	{
		code: "VN",
		name: "Vietnam",
		currencyCode: "VND",
		phoneCode: 84,
		provinces: []
	},
	{
		code: "VG",
		name: "Virgin Islands, British",
		currencyCode: "USD",
		phoneCode: 1284,
		provinces: []
	},
	{
		code: "WF",
		name: "Wallis And Futuna",
		currencyCode: "XPF",
		phoneCode: 681,
		provinces: []
	},
	{
		code: "EH",
		name: "Western Sahara",
		currencyCode: "MAD",
		phoneCode: 2,
		provinces: []
	},
	{
		code: "YE",
		name: "Yemen",
		currencyCode: "YER",
		phoneCode: 967,
		provinces: []
	},
	{
		code: "ZM",
		name: "Zambia",
		currencyCode: "ZMW",
		phoneCode: 260,
		provinces: []
	},
	{
		code: "ZW",
		name: "Zimbabwe",
		currencyCode: "USD",
		phoneCode: 263,
		provinces: []
	}
];
